# Generated by Django 5.1.6 on 2025-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcard',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
