# Generated by Django 5.1.6 on 2025-02-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_addcard_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
